## This file is a general .xdc for the Zybo Z7 Rev. B
## It is compatible with the Zybo Z7-20 and Zybo Z7-10
## To use it in a project:
## - uncomment the lines corresponding to used pins
## - rename the used ports (in each line, after get_ports) according to the top level signal names in the project

##Clock signal
set_property -dict {PACKAGE_PIN K17 IOSTANDARD LVCMOS33} [get_ports clk]
create_clock -period 8.000 -name sys_clk_pin -waveform {0.000 4.000} -add [get_ports clk]

##Switches
set_property -dict {PACKAGE_PIN G15 IOSTANDARD LVCMOS33} [get_ports {challenge[0]}]
set_property -dict {PACKAGE_PIN P15 IOSTANDARD LVCMOS33} [get_ports {challenge[1]}]
set_property -dict {PACKAGE_PIN W13 IOSTANDARD LVCMOS33} [get_ports {challenge[2]}]
set_property -dict {PACKAGE_PIN T16 IOSTANDARD LVCMOS33} [get_ports {challenge[3]}]


##Buttons
set_property -dict {PACKAGE_PIN K18 IOSTANDARD LVCMOS33} [get_ports rst]
set_property -dict {PACKAGE_PIN P16 IOSTANDARD LVCMOS33} [get_ports en]
#set_property -dict { PACKAGE_PIN K19   IOSTANDARD LVCMOS33 } [get_ports { challange[2] }]; #IO_L10P_T1_AD11P_35 Sch=btn[2]
#set_property -dict { PACKAGE_PIN Y16   IOSTANDARD LVCMOS33 } [get_ports { challange[3] }]; #IO_L7P_T1_34 Sch=btn[3]


##LEDs
set_property -dict {PACKAGE_PIN M14 IOSTANDARD LVCMOS33} [get_ports {led[0]}]
set_property -dict {PACKAGE_PIN M15 IOSTANDARD LVCMOS33} [get_ports {led[1]}]
#set_property -dict { PACKAGE_PIN G14   IOSTANDARD LVCMOS33 } [get_ports { led[2] }]; #IO_0_35 Sch=led[2]
#set_property -dict { PACKAGE_PIN D18   IOSTANDARD LVCMOS33 } [get_ports { led[3] }]; #IO_L3N_T0_DQS_AD1N_35 Sch=led[3]

set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets RO1/en]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets RO1/w1]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets RO1/w2]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets RO1/w3]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets RO1/w4]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets RO1/w5]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets RO1/w6]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets RO1/w7]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets RO1/w8]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets RO2/en]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets RO2/w1]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets RO2/w2]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets RO2/w3]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets RO2/w4]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets RO2/w5]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets RO2/w6]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets RO2/w7]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets RO2/w8]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets RO3/en]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets RO3/w1]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets RO3/w2]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets RO3/w3]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets RO3/w4]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets RO3/w5]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets RO3/w6]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets RO3/w7]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets RO3/w8]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets RO4/en]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets RO4/w1]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets RO4/w2]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets RO4/w3]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets RO4/w4]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets RO4/w5]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets RO4/w6]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets RO4/w7]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets RO4/w8]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets RO5/en]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets RO5/w1]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets RO5/w2]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets RO5/w3]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets RO5/w4]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets RO5/w5]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets RO5/w6]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets RO5/w7]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets RO5/w8]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets RO6/en]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets RO6/w1]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets RO6/w2]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets RO6/w3]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets RO6/w4]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets RO6/w5]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets RO6/w6]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets RO6/w7]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets RO6/w8]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets RO7/en]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets RO7/w1]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets RO7/w2]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets RO7/w3]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets RO7/w4]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets RO7/w5]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets RO7/w6]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets RO7/w7]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets RO7/w8]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets RO8/en]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets RO8/w1]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets RO8/w2]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets RO8/w3]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets RO8/w4]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets RO8/w5]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets RO8/w6]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets RO8/w7]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets RO8/w8]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets mux1/a0]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets mux1/a1]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets mux1/a2]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets mux1/a3]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets mux1/b_BUFG]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {mux1/sel[0]}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {mux1/sel[1]}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets mux2/a0]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets mux2/a1]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets mux2/a2]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets mux2/a3]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets mux2/b_BUFG]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {mux2/sel[0]}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {mux2/sel[1]}]

set_property BEL D6LUT [get_cells RO1/w4_inferred_i_1]
set_property LOC SLICE_X38Y46 [get_cells RO1/w4_inferred_i_1]
