set_property SRC_FILE_INFO {cfile:C:/Users/keyur/Documents/Vivado/PUF/PUF.srcs/constrs_1/new/Zybo-Z7-Master.xdc rfile:../../../PUF.srcs/constrs_1/new/Zybo-Z7-Master.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN K17 IOSTANDARD LVCMOS33} [get_ports clk]
set_property src_info {type:XDC file:1 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN G15 IOSTANDARD LVCMOS33} [get_ports {challenge[0]}]
set_property src_info {type:XDC file:1 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN P15 IOSTANDARD LVCMOS33} [get_ports {challenge[1]}]
set_property src_info {type:XDC file:1 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN W13 IOSTANDARD LVCMOS33} [get_ports {challenge[2]}]
set_property src_info {type:XDC file:1 line:15 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN T16 IOSTANDARD LVCMOS33} [get_ports {challenge[3]}]
set_property src_info {type:XDC file:1 line:19 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN K18 IOSTANDARD LVCMOS33} [get_ports rst]
set_property src_info {type:XDC file:1 line:20 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN P16 IOSTANDARD LVCMOS33} [get_ports en]
set_property src_info {type:XDC file:1 line:26 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN M14 IOSTANDARD LVCMOS33} [get_ports {led[0]}]
set_property src_info {type:XDC file:1 line:27 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN M15 IOSTANDARD LVCMOS33} [get_ports {led[1]}]
set_property src_info {type:XDC file:1 line:28 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN G14   IOSTANDARD LVCMOS33 } [get_ports { led[2] }]; #IO_0_35 Sch=led[2]
set_property src_info {type:XDC file:1 line:29 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN D18   IOSTANDARD LVCMOS33 } [get_ports { led[3] }]; #IO_L3N_T0_DQS_AD1N_35 Sch=led[3]
set_property src_info {type:XDC file:1 line:117 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL A6LUT [get_cells RO1/w4_inferred_i_1]
set_property src_info {type:XDC file:1 line:118 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X36Y44 [get_cells RO1/w4_inferred_i_1]
set_property src_info {type:XDC file:1 line:120 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D5LUT [get_cells RO1/w1_inferred_i_1]
set_property src_info {type:XDC file:1 line:121 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X36Y44 [get_cells RO1/w1_inferred_i_1]
set_property src_info {type:XDC file:1 line:122 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL C6LUT [get_cells RO1/w2_inferred_i_1]
set_property src_info {type:XDC file:1 line:123 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X36Y44 [get_cells RO1/w2_inferred_i_1]
set_property src_info {type:XDC file:1 line:124 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL B6LUT [get_cells RO1/w3_inferred_i_1]
set_property src_info {type:XDC file:1 line:125 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X36Y44 [get_cells RO1/w3_inferred_i_1]
set_property src_info {type:XDC file:1 line:126 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D6LUT [get_cells RO1/w5_inferred_i_1]
set_property src_info {type:XDC file:1 line:127 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X37Y44 [get_cells RO1/w5_inferred_i_1]
set_property src_info {type:XDC file:1 line:128 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL C6LUT [get_cells RO1/w6_inferred_i_1]
set_property src_info {type:XDC file:1 line:129 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X37Y44 [get_cells RO1/w6_inferred_i_1]
set_property src_info {type:XDC file:1 line:130 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL B6LUT [get_cells RO1/w7_inferred_i_1]
set_property src_info {type:XDC file:1 line:131 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X37Y44 [get_cells RO1/w7_inferred_i_1]
set_property src_info {type:XDC file:1 line:132 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL A6LUT [get_cells RO1/w8_inferred_i_1]
set_property src_info {type:XDC file:1 line:133 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X37Y44 [get_cells RO1/w8_inferred_i_1]
set_property src_info {type:XDC file:1 line:134 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D6LUT [get_cells RO2/w1_inferred_i_1]
set_property src_info {type:XDC file:1 line:135 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X36Y43 [get_cells RO2/w1_inferred_i_1]
set_property src_info {type:XDC file:1 line:136 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL C6LUT [get_cells RO2/w2_inferred_i_1]
set_property src_info {type:XDC file:1 line:137 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X36Y43 [get_cells RO2/w2_inferred_i_1]
set_property src_info {type:XDC file:1 line:138 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL B6LUT [get_cells RO2/w3_inferred_i_1]
set_property src_info {type:XDC file:1 line:139 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X36Y43 [get_cells RO2/w3_inferred_i_1]
set_property src_info {type:XDC file:1 line:140 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL A6LUT [get_cells RO2/w4_inferred_i_1]
set_property src_info {type:XDC file:1 line:141 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X36Y43 [get_cells RO2/w4_inferred_i_1]
set_property src_info {type:XDC file:1 line:142 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D6LUT [get_cells RO2/w5_inferred_i_1]
set_property src_info {type:XDC file:1 line:143 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X37Y43 [get_cells RO2/w5_inferred_i_1]
set_property src_info {type:XDC file:1 line:144 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL C5LUT [get_cells RO2/w6_inferred_i_1]
set_property src_info {type:XDC file:1 line:145 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X37Y43 [get_cells RO2/w6_inferred_i_1]
set_property src_info {type:XDC file:1 line:146 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL B5LUT [get_cells RO2/w7_inferred_i_1]
set_property src_info {type:XDC file:1 line:147 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X37Y43 [get_cells RO2/w7_inferred_i_1]
set_property src_info {type:XDC file:1 line:148 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL A6LUT [get_cells RO2/w8_inferred_i_1]
set_property src_info {type:XDC file:1 line:149 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X37Y43 [get_cells RO2/w8_inferred_i_1]
set_property src_info {type:XDC file:1 line:150 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D6LUT [get_cells RO3/w1_inferred_i_1]
set_property src_info {type:XDC file:1 line:151 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X36Y42 [get_cells RO3/w1_inferred_i_1]
set_property src_info {type:XDC file:1 line:152 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL C6LUT [get_cells RO3/w2_inferred_i_1]
set_property src_info {type:XDC file:1 line:153 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X36Y42 [get_cells RO3/w2_inferred_i_1]
set_property src_info {type:XDC file:1 line:154 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL B6LUT [get_cells RO3/w3_inferred_i_1]
set_property src_info {type:XDC file:1 line:155 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X36Y42 [get_cells RO3/w3_inferred_i_1]
set_property src_info {type:XDC file:1 line:156 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL A5LUT [get_cells RO3/w4_inferred_i_1]
set_property src_info {type:XDC file:1 line:157 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X36Y42 [get_cells RO3/w4_inferred_i_1]
set_property src_info {type:XDC file:1 line:158 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D6LUT [get_cells RO3/w5_inferred_i_1]
set_property src_info {type:XDC file:1 line:159 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X37Y42 [get_cells RO3/w5_inferred_i_1]
set_property src_info {type:XDC file:1 line:160 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL C5LUT [get_cells RO3/w6_inferred_i_1]
set_property src_info {type:XDC file:1 line:161 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X37Y42 [get_cells RO3/w6_inferred_i_1]
set_property src_info {type:XDC file:1 line:162 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL B5LUT [get_cells RO3/w7_inferred_i_1]
set_property src_info {type:XDC file:1 line:163 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X37Y42 [get_cells RO3/w7_inferred_i_1]
set_property src_info {type:XDC file:1 line:164 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL A6LUT [get_cells RO3/w8_inferred_i_1]
set_property src_info {type:XDC file:1 line:165 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X37Y42 [get_cells RO3/w8_inferred_i_1]
set_property src_info {type:XDC file:1 line:166 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D5LUT [get_cells RO4/w1_inferred_i_1]
set_property src_info {type:XDC file:1 line:167 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X36Y41 [get_cells RO4/w1_inferred_i_1]
set_property src_info {type:XDC file:1 line:168 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL C6LUT [get_cells RO4/w2_inferred_i_1]
set_property src_info {type:XDC file:1 line:169 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X36Y41 [get_cells RO4/w2_inferred_i_1]
set_property src_info {type:XDC file:1 line:170 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL B6LUT [get_cells RO4/w3_inferred_i_1]
set_property src_info {type:XDC file:1 line:171 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X36Y41 [get_cells RO4/w3_inferred_i_1]
set_property src_info {type:XDC file:1 line:172 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL A6LUT [get_cells RO4/w4_inferred_i_1]
set_property src_info {type:XDC file:1 line:173 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X36Y41 [get_cells RO4/w4_inferred_i_1]
set_property src_info {type:XDC file:1 line:174 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D6LUT [get_cells RO4/w5_inferred_i_1]
set_property src_info {type:XDC file:1 line:175 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X37Y41 [get_cells RO4/w5_inferred_i_1]
set_property src_info {type:XDC file:1 line:176 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL C6LUT [get_cells RO4/w6_inferred_i_1]
set_property src_info {type:XDC file:1 line:177 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X37Y41 [get_cells RO4/w6_inferred_i_1]
set_property src_info {type:XDC file:1 line:178 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL B6LUT [get_cells RO4/w7_inferred_i_1]
set_property src_info {type:XDC file:1 line:179 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X37Y41 [get_cells RO4/w7_inferred_i_1]
set_property src_info {type:XDC file:1 line:180 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL A6LUT [get_cells RO4/w8_inferred_i_1]
set_property src_info {type:XDC file:1 line:181 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X37Y41 [get_cells RO4/w8_inferred_i_1]
set_property src_info {type:XDC file:1 line:182 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D6LUT [get_cells RO5/w1_inferred_i_1]
set_property src_info {type:XDC file:1 line:183 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X36Y40 [get_cells RO5/w1_inferred_i_1]
set_property src_info {type:XDC file:1 line:184 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL C6LUT [get_cells RO5/w2_inferred_i_1]
set_property src_info {type:XDC file:1 line:185 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X36Y40 [get_cells RO5/w2_inferred_i_1]
set_property src_info {type:XDC file:1 line:186 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL B6LUT [get_cells RO5/w3_inferred_i_1]
set_property src_info {type:XDC file:1 line:187 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X36Y40 [get_cells RO5/w3_inferred_i_1]
set_property src_info {type:XDC file:1 line:188 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL A6LUT [get_cells RO5/w4_inferred_i_1]
set_property src_info {type:XDC file:1 line:189 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X36Y40 [get_cells RO5/w4_inferred_i_1]
set_property src_info {type:XDC file:1 line:190 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D6LUT [get_cells RO5/w5_inferred_i_1]
set_property src_info {type:XDC file:1 line:191 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X37Y40 [get_cells RO5/w5_inferred_i_1]
set_property src_info {type:XDC file:1 line:192 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL C6LUT [get_cells RO5/w6_inferred_i_1]
set_property src_info {type:XDC file:1 line:193 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X37Y40 [get_cells RO5/w6_inferred_i_1]
set_property src_info {type:XDC file:1 line:194 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL B6LUT [get_cells RO5/w7_inferred_i_1]
set_property src_info {type:XDC file:1 line:195 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X37Y40 [get_cells RO5/w7_inferred_i_1]
set_property src_info {type:XDC file:1 line:196 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL A6LUT [get_cells RO5/w8_inferred_i_1]
set_property src_info {type:XDC file:1 line:197 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X37Y40 [get_cells RO5/w8_inferred_i_1]
set_property src_info {type:XDC file:1 line:198 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL C6LUT [get_cells RO6/w2_inferred_i_1]
set_property src_info {type:XDC file:1 line:199 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X36Y39 [get_cells RO6/w2_inferred_i_1]
set_property src_info {type:XDC file:1 line:200 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL B6LUT [get_cells RO6/w3_inferred_i_1]
set_property src_info {type:XDC file:1 line:201 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X36Y39 [get_cells RO6/w3_inferred_i_1]
set_property src_info {type:XDC file:1 line:202 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL A6LUT [get_cells RO6/w4_inferred_i_1]
set_property src_info {type:XDC file:1 line:203 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X36Y39 [get_cells RO6/w4_inferred_i_1]
set_property src_info {type:XDC file:1 line:204 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D5LUT [get_cells RO6/w1_inferred_i_1]
set_property src_info {type:XDC file:1 line:205 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X36Y39 [get_cells RO6/w1_inferred_i_1]
set_property src_info {type:XDC file:1 line:206 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D5LUT [get_cells RO6/w5_inferred_i_1]
set_property src_info {type:XDC file:1 line:207 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X37Y39 [get_cells RO6/w5_inferred_i_1]
set_property src_info {type:XDC file:1 line:208 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL C5LUT [get_cells RO6/w6_inferred_i_1]
set_property src_info {type:XDC file:1 line:209 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X37Y39 [get_cells RO6/w6_inferred_i_1]
set_property src_info {type:XDC file:1 line:210 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL B6LUT [get_cells RO6/w7_inferred_i_1]
set_property src_info {type:XDC file:1 line:211 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X37Y39 [get_cells RO6/w7_inferred_i_1]
set_property src_info {type:XDC file:1 line:212 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL A6LUT [get_cells RO6/w8_inferred_i_1]
set_property src_info {type:XDC file:1 line:213 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X37Y39 [get_cells RO6/w8_inferred_i_1]
set_property src_info {type:XDC file:1 line:214 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D6LUT [get_cells RO7/w1_inferred_i_1]
set_property src_info {type:XDC file:1 line:215 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X36Y38 [get_cells RO7/w1_inferred_i_1]
set_property src_info {type:XDC file:1 line:216 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL C6LUT [get_cells RO7/w2_inferred_i_1]
set_property src_info {type:XDC file:1 line:217 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X36Y38 [get_cells RO7/w2_inferred_i_1]
set_property src_info {type:XDC file:1 line:218 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL B6LUT [get_cells RO7/w3_inferred_i_1]
set_property src_info {type:XDC file:1 line:219 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X36Y38 [get_cells RO7/w3_inferred_i_1]
set_property src_info {type:XDC file:1 line:220 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL A6LUT [get_cells RO7/w4_inferred_i_1]
set_property src_info {type:XDC file:1 line:221 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X36Y38 [get_cells RO7/w4_inferred_i_1]
set_property src_info {type:XDC file:1 line:222 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D6LUT [get_cells RO7/w5_inferred_i_1]
set_property src_info {type:XDC file:1 line:223 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X37Y38 [get_cells RO7/w5_inferred_i_1]
set_property src_info {type:XDC file:1 line:224 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL C6LUT [get_cells RO7/w6_inferred_i_1]
set_property src_info {type:XDC file:1 line:225 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X37Y38 [get_cells RO7/w6_inferred_i_1]
set_property src_info {type:XDC file:1 line:226 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL B6LUT [get_cells RO7/w7_inferred_i_1]
set_property src_info {type:XDC file:1 line:227 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X37Y38 [get_cells RO7/w7_inferred_i_1]
set_property src_info {type:XDC file:1 line:228 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL A6LUT [get_cells RO7/w8_inferred_i_1]
set_property src_info {type:XDC file:1 line:229 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X37Y38 [get_cells RO7/w8_inferred_i_1]
set_property src_info {type:XDC file:1 line:230 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D5LUT [get_cells RO8/w1_inferred_i_1]
set_property src_info {type:XDC file:1 line:231 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X36Y37 [get_cells RO8/w1_inferred_i_1]
set_property src_info {type:XDC file:1 line:232 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL C6LUT [get_cells RO8/w2_inferred_i_1]
set_property src_info {type:XDC file:1 line:233 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X36Y37 [get_cells RO8/w2_inferred_i_1]
set_property src_info {type:XDC file:1 line:234 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL B6LUT [get_cells RO8/w3_inferred_i_1]
set_property src_info {type:XDC file:1 line:235 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X36Y37 [get_cells RO8/w3_inferred_i_1]
set_property src_info {type:XDC file:1 line:236 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL A6LUT [get_cells RO8/w4_inferred_i_1]
set_property src_info {type:XDC file:1 line:237 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X36Y37 [get_cells RO8/w4_inferred_i_1]
set_property src_info {type:XDC file:1 line:238 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D6LUT [get_cells RO8/w5_inferred_i_1]
set_property src_info {type:XDC file:1 line:239 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X37Y37 [get_cells RO8/w5_inferred_i_1]
set_property src_info {type:XDC file:1 line:240 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL C6LUT [get_cells RO8/w6_inferred_i_1]
set_property src_info {type:XDC file:1 line:241 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X37Y37 [get_cells RO8/w6_inferred_i_1]
set_property src_info {type:XDC file:1 line:242 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL B6LUT [get_cells RO8/w7_inferred_i_1]
set_property src_info {type:XDC file:1 line:243 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X37Y37 [get_cells RO8/w7_inferred_i_1]
set_property src_info {type:XDC file:1 line:244 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL A6LUT [get_cells RO8/w8_inferred_i_1]
set_property src_info {type:XDC file:1 line:245 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X37Y37 [get_cells RO8/w8_inferred_i_1]
set_property src_info {type:XDC file:1 line:246 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D6LUT [get_cells mux1/b_INST_0]
set_property src_info {type:XDC file:1 line:247 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X39Y42 [get_cells mux1/b_INST_0]
set_property src_info {type:XDC file:1 line:248 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D6LUT [get_cells mux2/b_INST_0]
set_property src_info {type:XDC file:1 line:249 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X39Y38 [get_cells mux2/b_INST_0]
set_property src_info {type:XDC file:1 line:250 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL DFF [get_cells mux1_prev_reg]
set_property src_info {type:XDC file:1 line:251 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X39Y43 [get_cells mux1_prev_reg]
